name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Add riscv64 rust target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Install riscv64-gcc
      run: sudo apt-get install -y gcc-riscv64-unknown-elf
    - name: Install llvm 16
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 16 && rm llvm.sh
    - name: Build
      run: cargo build --verbose --target=riscv64imac-unknown-none-elf
    - name: Build fuzzing & coverage binaries
      run: make -C tests
    - name: Run tests
      run: cd tests; cargo test --verbose -- --test-threads=1
